# Generated by Django 5.0.4 on 2024-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecu_name', models.CharField(max_length=20)),
                ('customer_number', models.CharField(max_length=15)),
                ('hw_number', models.CharField(max_length=10)),
                ('sw_number', models.CharField(max_length=10)),
                ('ecu_comment', models.TextField(max_length=70)),
                ('testing', models.CharField(max_length=5)),
            ],
        ),
    ]
