# Generated by Django 5.0.4 on 2024-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ecu', '0002_ecu_al_part_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecu',
            name='al_part_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
