# Generated by Django 5.0.4 on 2024-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ecu', '0003_alter_ecu_al_part_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecu',
            name='testing',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
