# Generated by Django 5.0.4 on 2024-05-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ecu', '0005_alter_ecu_ecu_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecu',
            name='ecu_comment',
            field=models.CharField(max_length=30),
        ),
    ]
