# Generated by Django 5.0.4 on 2024-05-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ecu', '0006_alter_ecu_ecu_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecu',
            name='testing',
        ),
        migrations.AddField(
            model_name='ecu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
