# Generated by Django 5.0.4 on 2024-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ecu', '0009_ecu_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecu',
            name='ecu_comment',
        ),
        migrations.AddField(
            model_name='ecu',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ecu',
            name='ecu_description',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='al_part_no',
            field=models.CharField(max_length=101),
        ),
    ]
