# Generated by Django 5.0.4 on 2024-07-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ecu', '0010_remove_ecu_ecu_comment_ecu_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecu',
            name='al_part_no',
            field=models.CharField(blank=True, max_length=101, null=True),
        ),
    ]
